print("aabbcc&123".isalnum())
print("hello9".isalpha())
print("123".isdigit())
print("123".isnumeric())
print("1二".isdigit())
print("1二".isnumeric())
str1="hi,Python!hi,Java"
print(str1.startswith("hi"))
print(str1.endswith("Java"))
print(str1.startswith("hi",3))
print(str1.endswith("hi",3,12))
print(len(str1))
print(max(str1),min(str1))
print(str1.count("hi"))
str2="hi,Python,hi,Java!"
print(str2.split())
print(str2.split(","))
print(str2.split(",",2))
lst=['hi','python','java']
s=''
print(s.join(lst))
